#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.A8F{1,0,7.2,1
#
am335x_app.xa8fg: package/cfg/am335x_app.xa8fg.mak

clean::
	-$(RM) package/cfg/am335x_app.xa8fg.mak
