/*
 * v4.01 snmp/mibvars.c
 * April 23, 2013
 * Distributed per InterNiche ref US1613-2
 */
/*  mibvars.c

    C code file Generated by InterNiche Technologies Inc. MIB Compiler
    Copyright 1993-2003 by InterNiche Technologies Inc.
*/

#include <Profinet/snmp/Include/snmpagt.h>

/** @brief OIDs supported by this application */
struct variable variables[] =
{
    {{1, 0, 8802, 1, 1, 2, 1, 1, 1, 0},  10, INTEGER, LLDPMESSAGETXINTERVAL, RWRITE, var_lldpConfiguration },
    {{1, 0, 8802, 1, 1, 2, 1, 1, 2, 0},  10, INTEGER, LLDPMESSAGETXHOLDMULTIPLIER, RWRITE, var_lldpConfiguration },
    {{1, 0, 8802, 1, 1, 2, 1, 1, 3, 0},  10, INTEGER, LLDPREINITDELAY, RWRITE, var_lldpConfiguration },
    {{1, 0, 8802, 1, 1, 2, 1, 1, 4, 0},  10, INTEGER, LLDPTXDELAY, RWRITE, var_lldpConfiguration },
    {{1, 0, 8802, 1, 1, 2, 1, 1, 5, 0},  10, INTEGER, LLDPNOTIFICATIONINTERVAL, RWRITE, var_lldpConfiguration },
    {{1, 0, 8802, 1, 1, 2, 1, 1, 6, 1, 2, 0xFF},   12, INTEGER, LLDPPORTCONFIGADMINSTATUS, RWRITE, var_lldpPortConfigEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 1, 6, 1, 3, 0xFF},   12, INTEGER, LLDPPORTCONFIGNOTIFICATIONENABLE, RWRITE, var_lldpPortConfigEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 1, 6, 1, 4, 0xFF},   12, BITS, LLDPPORTCONFIGTLVSTXENABLE, RWRITE, var_lldpPortConfigEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 1, 7, 1, 1, 0xFF},   12, STRING, LLDPCONFIGMANADDRPORTSTXENABLE, RWRITE, var_lldpConfigManAddrEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 1, 0},  10, TIMETICKS, LLDPSTATSREMTABLESLASTCHANGETIME, RONLY, var_lldpStatistics },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 2, 0},  10, GAUGE, LLDPSTATSREMTABLESINSERTS, RONLY, var_lldpStatistics },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 3, 0},  10, GAUGE, LLDPSTATSREMTABLESDELETES, RONLY, var_lldpStatistics },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 4, 0},  10, GAUGE, LLDPSTATSREMTABLESDROPS, RONLY, var_lldpStatistics },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 5, 0},  10, GAUGE, LLDPSTATSREMTABLESAGEOUTS, RONLY, var_lldpStatistics },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 6, 1, 2, 0xFF},   12, COUNTER, LLDPSTATSTXPORTFRAMESTOTAL, RONLY, var_lldpStatsTxPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 7, 1, 2, 0xFF},   12, COUNTER, LLDPSTATSRXPORTFRAMESDISCARDEDTOTAL, RONLY, var_lldpStatsRxPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 7, 1, 3, 0xFF},   12, COUNTER, LLDPSTATSRXPORTFRAMESERRORS, RONLY, var_lldpStatsRxPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 7, 1, 4, 0xFF},   12, COUNTER, LLDPSTATSRXPORTFRAMESTOTAL, RONLY, var_lldpStatsRxPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 7, 1, 5, 0xFF},   12, COUNTER, LLDPSTATSRXPORTTLVSDISCARDEDTOTAL, RONLY, var_lldpStatsRxPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 7, 1, 6, 0xFF},   12, COUNTER, LLDPSTATSRXPORTTLVSUNRECOGNIZEDTOTAL, RONLY, var_lldpStatsRxPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 2, 7, 1, 7, 0xFF},   12, GAUGE, LLDPSTATSRXPORTAGEOUTSTOTAL, RONLY, var_lldpStatsRxPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 1, 0},  10, INTEGER, LLDPLOCCHASSISIDSUBTYPE, RONLY, var_lldpLocalSystemData },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 2, 0},  10, STRING, LLDPLOCCHASSISID, RONLY, var_lldpLocalSystemData },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 3, 0},  10, STRING, LLDPLOCSYSNAME, RONLY, var_lldpLocalSystemData },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 4, 0},  10, STRING, LLDPLOCSYSDESC, RONLY, var_lldpLocalSystemData },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 5, 0},  10, BITS, LLDPLOCSYSCAPSUPPORTED, RONLY, var_lldpLocalSystemData },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 6, 0},  10, BITS, LLDPLOCSYSCAPENABLED, RONLY, var_lldpLocalSystemData },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 7, 1, 2, 0xFF},   12, INTEGER, LLDPLOCPORTIDSUBTYPE, RONLY, var_lldpLocPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 7, 1, 3, 0xFF},   12, STRING, LLDPLOCPORTID, RONLY, var_lldpLocPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 7, 1, 4, 0xFF},   12, STRING, LLDPLOCPORTDESC, RONLY, var_lldpLocPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 8, 1, 3, 0xFF},   12, INTEGER, LLDPLOCMANADDRLEN, RONLY, var_lldpLocManAddrEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 8, 1, 4, 0xFF},   12, INTEGER, LLDPLOCMANADDRIFSUBTYPE, RONLY, var_lldpLocManAddrEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 8, 1, 5, 0xFF},   12, INTEGER, LLDPLOCMANADDRIFID, RONLY, var_lldpLocManAddrEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 3, 8, 1, 6, 0xFF},   12, OBJID, LLDPLOCMANADDROID, RONLY, var_lldpLocManAddrEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 1, 1, 4, 0xFF},   12, INTEGER, LLDPREMCHASSISIDSUBTYPE, RONLY, var_lldpRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 1, 1, 5, 0xFF},   12, STRING, LLDPREMCHASSISID, RONLY, var_lldpRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 1, 1, 6, 0xFF},   12, INTEGER, LLDPREMPORTIDSUBTYPE, RONLY, var_lldpRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 1, 1, 7, 0xFF},   12, STRING, LLDPREMPORTID, RONLY, var_lldpRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 1, 1, 8, 0xFF},   12, STRING, LLDPREMPORTDESC, RONLY, var_lldpRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 1, 1, 9, 0xFF},   12, STRING, LLDPREMSYSNAME, RONLY, var_lldpRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 1, 1, 10, 0xFF},  12, STRING, LLDPREMSYSDESC, RONLY, var_lldpRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 1, 1, 11, 0xFF},  12, BITS, LLDPREMSYSCAPSUPPORTED, RONLY, var_lldpRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 1, 1, 12, 0xFF},  12, BITS, LLDPREMSYSCAPENABLED, RONLY, var_lldpRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 2, 1, 3, 0xFF},   12, INTEGER, LLDPREMMANADDRIFSUBTYPE, RONLY, var_lldpRemManAddrEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 2, 1, 4, 0xFF},   12, INTEGER, LLDPREMMANADDRIFID, RONLY, var_lldpRemManAddrEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 2, 1, 5, 0xFF},   12, OBJID, LLDPREMMANADDROID, RONLY, var_lldpRemManAddrEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 3, 1, 2, 0xFF},   12, STRING, LLDPREMUNKNOWNTLVINFO, RONLY, var_lldpRemUnknownTLVEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 4, 4, 1, 4, 0xFF},   12, STRING, LLDPREMORGDEFINFO, RONLY, var_lldpRemOrgDefInfoEntry },

    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 1, 1, 1, 1, 0xFF},  15, INTEGER, LLDPXPNOCONFIGSPDTXENABLE, RWRITE, var_lldpXPnoConfigEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 1, 1, 1, 2, 0xFF},  15, INTEGER, LLDPXPNOCONFIGPORTSTATUSTXENABLE, RWRITE, var_lldpXPnoConfigEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 1, 1, 1, 3, 0xFF},  15, INTEGER, LLDPXPNOCONFIGALIASTXENABLE, RWRITE, var_lldpXPnoConfigEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 1, 1, 1, 4, 0xFF},  15, INTEGER, LLDPXPNOCONFIGMRPTXENABLE, RWRITE, var_lldpXPnoConfigEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 1, 1, 1, 5, 0xFF},  15, INTEGER, LLDPXPNOCONFIGPTCPTXENABLE, RWRITE, var_lldpXPnoConfigEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 1, 0xFF},  15, UNSIGNED32, LLDPXPNOLOCLPDVALUE, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 2, 0xFF},  15, UNSIGNED32, LLDPXPNOLOCPORTTXDVALUE, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 3, 0xFF},  15, UNSIGNED32, LLDPXPNOLOCPORTRXDVALUE, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 4, 0xFF},  15, INTEGER, LLDPXPNOLOCPORTSTATUSRT2, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 5, 0xFF},  15, INTEGER, LLDPXPNOLOCPORTSTATUSRT3, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 6, 0xFF},  15, STRING, LLDPXPNOLOCPORTNOS, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 7, 0xFF},  15, STRING, LLDPXPNOLOCPORTMRPUUID, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 8, 0xFF},  15, INTEGER, LLDPXPNOLOCPORTMRRTSTATUS, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 9, 0xFF},  15, STRING, LLDPXPNOLOCPORTPTCPMASTER, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 10, 0xFF}, 15, STRING, LLDPXPNOLOCPORTPTCPSUBDOMAINUUID, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 11, 0xFF}, 15, STRING, LLDPXPNOLOCPORTPTCPIRDATAUUID, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 12, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTMODERT3, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 13, 0xFF}, 15, UNSIGNED32, LLDPXPNOLOCPORTPERIODLENGTH, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 14, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTPERIODVALIDITY, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 15, 0xFF}, 15, UNSIGNED32, LLDPXPNOLOCPORTREDOFFSET, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 16, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTREDVALIDITY, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 17, 0xFF}, 15, UNSIGNED32, LLDPXPNOLOCPORTORANGEOFFSET, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 18, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTORANGEVALIDITY, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 19, 0xFF}, 15, UNSIGNED32, LLDPXPNOLOCPORTGREENOFFSET, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 20, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTGREENVALIDITY, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 21, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTSTATUSRT3OPTIMIZATIONSUPPORTED, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 22, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTSTATUSRT3PREAMBLESHORTENINGSUPPORTED, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 23, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTSTATUSRT3PREAMBLESHORTENING, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 24, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTSTATUSRT3FRAGMENTATIONSUPPORTED, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 2, 1, 1, 25, 0xFF}, 15, INTEGER, LLDPXPNOLOCPORTSTATUSRT3FRAGMENTATION, RONLY, var_lldpXPnoLocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 1, 0xFF},  15, UNSIGNED32, LLDPXPNOREMLPDVALUE, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 2, 0xFF},  15, UNSIGNED32, LLDPXPNOREMPORTTXDVALUE, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 3, 0xFF},  15, UNSIGNED32, LLDPXPNOREMPORTRXDVALUE, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 4, 0xFF},  15, INTEGER, LLDPXPNOREMPORTSTATUSRT2, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 5, 0xFF},  15, INTEGER, LLDPXPNOREMPORTSTATUSRT3, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 6, 0xFF},  15, STRING, LLDPXPNOREMPORTNOS, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 7, 0xFF},  15, STRING, LLDPXPNOREMPORTMRPUUID, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 8, 0xFF},  15, INTEGER, LLDPXPNOREMPORTMRRTSTATUS, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 9, 0xFF},  15, STRING, LLDPXPNOREMPORTPTCPMASTER, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 10, 0xFF}, 15, STRING, LLDPXPNOREMPORTPTCPSUBDOMAINUUID, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 11, 0xFF}, 15, STRING, LLDPXPNOREMPORTPTCPIRDATAUUID, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 12, 0xFF}, 15, INTEGER, LLDPXPNOREMPORTMODERT3, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 13, 0xFF}, 15, UNSIGNED32, LLDPXPNOREMPORTPERIODLENGTH, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 14, 0xFF}, 15, INTEGER, LLDPXPNOREMPORTPERIODVALIDITY, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 15, 0xFF}, 15, UNSIGNED32, LLDPXPNOREMPORTREDOFFSET, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 16, 0xFF}, 15, INTEGER, LLDPXPNOREMPORTREDVALIDITY, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 17, 0xFF}, 15, UNSIGNED32, LLDPXPNOREMPORTORANGEOFFSET, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 18, 0xFF}, 15, INTEGER, LLDPXPNOREMPORTORANGEVALIDITY, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 19, 0xFF}, 15, UNSIGNED32, LLDPXPNOREMPORTGREENOFFSET, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 20, 0xFF}, 15, INTEGER, LLDPXPNOREMPORTGREENVALIDITY, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 21, 0xFF}, 15, INTEGER, LLDPXPNOREMPORTSTATUSRT3PREAMBLESHORTENING, RONLY, var_lldpXPnoRemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 3791, 1, 3, 1, 1, 22, 0xFF}, 15, INTEGER, LLDPXPNOREMPORTSTATUSRT3FRAGMENTATION, RONLY, var_lldpXPnoRemEntry },

    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 1, 1, 1, 1, 0xFF},  15, BITS, LLDPXDOT3PORTCONFIGTLVSTXENABLE, RWRITE, var_lldpXdot3PortConfigEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 1, 1, 1, 0xFF},  15, INTEGER, LLDPXDOT3LOCPORTAUTONEGSUPPORTED, RONLY, var_lldpXdot3LocPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 1, 1, 2, 0xFF},  15, INTEGER, LLDPXDOT3LOCPORTAUTONEGENABLED, RONLY, var_lldpXdot3LocPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 1, 1, 3, 0xFF},  15, STRING, LLDPXDOT3LOCPORTAUTONEGADVERTISEDCAP, RONLY, var_lldpXdot3LocPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 1, 1, 4, 0xFF},  15, INTEGER, LLDPXDOT3LOCPORTOPERMAUTYPE, RONLY, var_lldpXdot3LocPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 2, 1, 1, 0xFF},  15, INTEGER, LLDPXDOT3LOCPOWERPORTCLASS, RONLY, var_lldpXdot3LocPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 2, 1, 2, 0xFF},  15, INTEGER, LLDPXDOT3LOCPOWERMDISUPPORTED, RONLY, var_lldpXdot3LocPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 2, 1, 3, 0xFF},  15, INTEGER, LLDPXDOT3LOCPOWERMDIENABLED, RONLY, var_lldpXdot3LocPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 2, 1, 4, 0xFF},  15, INTEGER, LLDPXDOT3LOCPOWERPAIRCONTROLABLE, RONLY, var_lldpXdot3LocPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 2, 1, 5, 0xFF},  15, INTEGER, LLDPXDOT3LOCPOWERPAIRS, RONLY, var_lldpXdot3LocPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 2, 1, 6, 0xFF},  15, INTEGER, LLDPXDOT3LOCPOWERCLASS, RONLY, var_lldpXdot3LocPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 3, 1, 1, 0xFF},  15, BITS, LLDPXDOT3LOCLINKAGGSTATUS, RONLY, var_lldpXdot3LocLinkAggEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 3, 1, 2, 0xFF},  15, INTEGER, LLDPXDOT3LOCLINKAGGPORTID, RONLY, var_lldpXdot3LocLinkAggEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 2, 4, 1, 1, 0xFF},  15, INTEGER, LLDPXDOT3LOCMAXFRAMESIZE, RONLY, var_lldpXdot3LocMaxFrameSizeEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 1, 1, 1, 0xFF},  15, INTEGER, LLDPXDOT3REMPORTAUTONEGSUPPORTED, RONLY, var_lldpXdot3RemPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 1, 1, 2, 0xFF},  15, INTEGER, LLDPXDOT3REMPORTAUTONEGENABLED, RONLY, var_lldpXdot3RemPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 1, 1, 3, 0xFF},  15, STRING, LLDPXDOT3REMPORTAUTONEGADVERTISEDCAP, RONLY, var_lldpXdot3RemPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 1, 1, 4, 0xFF},  15, INTEGER, LLDPXDOT3REMPORTOPERMAUTYPE, RONLY, var_lldpXdot3RemPortEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 2, 1, 1, 0xFF},  15, INTEGER, LLDPXDOT3REMPOWERPORTCLASS, RONLY, var_lldpXdot3RemPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 2, 1, 2, 0xFF},  15, INTEGER, LLDPXDOT3REMPOWERMDISUPPORTED, RONLY, var_lldpXdot3RemPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 2, 1, 3, 0xFF},  15, INTEGER, LLDPXDOT3REMPOWERMDIENABLED, RONLY, var_lldpXdot3RemPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 2, 1, 4, 0xFF},  15, INTEGER, LLDPXDOT3REMPOWERPAIRCONTROLABLE, RONLY, var_lldpXdot3RemPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 2, 1, 5, 0xFF},  15, INTEGER, LLDPXDOT3REMPOWERPAIRS, RONLY, var_lldpXdot3RemPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 2, 1, 6, 0xFF},  15, INTEGER, LLDPXDOT3REMPOWERCLASS, RONLY, var_lldpXdot3RemPowerEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 3, 1, 1, 0xFF},  15, BITS, LLDPXDOT3REMLINKAGGSTATUS, RONLY, var_lldpXdot3RemLinkAggEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 3, 1, 2, 0xFF},  15, INTEGER, LLDPXDOT3REMLINKAGGPORTID, RONLY, var_lldpXdot3RemLinkAggEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 4623, 1, 3, 4, 1, 1, 0xFF},  15, INTEGER, LLDPXDOT3REMMAXFRAMESIZE, RONLY, var_lldpXdot3RemMaxFrameSizeEntry },

    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 1, 1, 1, 1, 0xFF}, 15, INTEGER, LLDPXDOT1CONFIGPORTVLANTXENABLE, RWRITE, var_lldpXdot1ConfigPortVlanEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 1, 2, 1, 1, 0xFF}, 15, INTEGER, LLDPXDOT1CONFIGVLANNAMETXENABLE, RWRITE, var_lldpXdot1ConfigVlanNameEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 1, 3, 1, 1, 0xFF}, 15, INTEGER, LLDPXDOT1CONFIGPROTOVLANTXENABLE, RWRITE, var_lldpXdot1ConfigProtoVlanEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 1, 4, 1, 1, 0xFF}, 15, INTEGER, LLDPXDOT1CONFIGPROTOCOLTXENABLE, RWRITE, var_lldpXdot1ConfigProtocolEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 2, 1, 1, 1, 0xFF}, 15, INTEGER, LLDPXDOT1LOCPORTVLANID, RONLY, var_lldpXdot1LocEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 2, 2, 1, 2, 0xFF}, 15, INTEGER, LLDPXDOT1LOCPROTOVLANSUPPORTED, RONLY, var_lldpXdot1LocProtoVlanEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 2, 2, 1, 3, 0xFF}, 15, INTEGER, LLDPXDOT1LOCPROTOVLANENABLED, RONLY, var_lldpXdot1LocProtoVlanEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 2, 3, 1, 2, 0xFF}, 15, STRING, LLDPXDOT1LOCVLANNAME, RONLY, var_lldpXdot1LocVlanNameEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 2, 4, 1, 2, 0xFF}, 15, STRING, LLDPXDOT1LOCPROTOCOLID, RONLY, var_lldpXdot1LocProtocolEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 3, 1, 1, 1, 0xFF}, 15, INTEGER, LLDPXDOT1REMPORTVLANID, RONLY, var_lldpXdot1RemEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 3, 2, 1, 2, 0xFF}, 15, INTEGER, LLDPXDOT1REMPROTOVLANSUPPORTED, RONLY, var_lldpXdot1RemProtoVlanEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 3, 2, 1, 3, 0xFF}, 15, INTEGER, LLDPXDOT1REMPROTOVLANENABLED, RONLY, var_lldpXdot1RemProtoVlanEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 3, 3, 1, 2, 0xFF}, 15, STRING, LLDPXDOT1REMVLANNAME, RONLY, var_lldpXdot1RemVlanNameEntry },
    {{1, 0, 8802, 1, 1, 2, 1, 5, 32962, 1, 3, 4, 1, 2, 0xFF}, 15, STRING, LLDPXDOT1REMPROTOCOLID, RONLY, var_lldpXdot1RemProtocolEntry },


    {{1, 3, 6, 1, 2, 1, 1, 1, 0},   9, STRING, SYSDESCR, RONLY, var_system , {3, 1, 1, {0, 255}}},
    {{1, 3, 6, 1, 2, 1, 1, 2, 0},   9, OBJID, SYSOBJECTID, RONLY, var_system , {0}},
    {{1, 3, 6, 1, 2, 1, 1, 3, 0},   9, TIMETICKS, SYSUPTIME, RONLY, var_system , {0}},
    {{1, 3, 6, 1, 2, 1, 1, 4, 0},   9, STRING, SYSCONTACT, RWRITE, var_system , {3, 1, 1, {0, 255}}},
    {{1, 3, 6, 1, 2, 1, 1, 5, 0},   9, STRING, SYSNAME, RWRITE, var_system , {3, 1, 1, {0, 255}}},
    {{1, 3, 6, 1, 2, 1, 1, 6, 0},   9, STRING, SYSLOCATION, RWRITE, var_system , {3, 1, 1, {0, 255}}},
    {{1, 3, 6, 1, 2, 1, 1, 7, 0},   9, INTEGER, SYSSERVICES, RONLY, var_system },
    {{1, 3, 6, 1, 2, 1, 2, 1, 0},   9, INTEGER, IFNUMBER, RONLY, var_interfaces },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 1, 0xFF},    11, INTEGER, IFINDEX, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 2, 0xFF},    11, STRING, IFDESCR, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 3, 0xFF},    11, INTEGER, IFTYPE, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 4, 0xFF},    11, INTEGER, IFMTU, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 5, 0xFF},    11, GAUGE, IFSPEED, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 6, 0xFF},    11, STRING, IFPHYSADDRESS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 7, 0xFF},    11, INTEGER, IFADMINSTATUS, RWRITE, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 8, 0xFF},    11, INTEGER, IFOPERSTATUS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 9, 0xFF},    11, TIMETICKS, IFLASTCHANGE, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 10, 0xFF},   11, COUNTER, IFINOCTETS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 11, 0xFF},   11, COUNTER, IFINUCASTPKTS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 12, 0xFF},   11, COUNTER, IFINNUCASTPKTS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 13, 0xFF},   11, COUNTER, IFINDISCARDS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 14, 0xFF},   11, COUNTER, IFINERRORS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 15, 0xFF},   11, COUNTER, IFINUNKNOWNPROTOS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 16, 0xFF},   11, COUNTER, IFOUTOCTETS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 17, 0xFF},   11, COUNTER, IFOUTUCASTPKTS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 18, 0xFF},   11, COUNTER, IFOUTNUCASTPKTS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 19, 0xFF},   11, COUNTER, IFOUTDISCARDS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 20, 0xFF},   11, COUNTER, IFOUTERRORS, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 21, 0xFF},   11, GAUGE, IFOUTQLEN, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 2, 1, 2, 2, 1, 22, 0xFF},   11, OBJID, IFSPECIFIC, RONLY, var_ifEntry },
    {{1, 3, 6, 1, 6, 3, 10, 2, 1, 1, 0},    11, STRING, SNMPENGINEID, RONLY, var_snmpEngine },


};

int num_variables = sizeof(variables) / sizeof(struct variable);


/* As variables[] is put in FAR_DATA segment, code that implements
   get_num_variables() and get_variables_arr() is compiler dependent.
   Hence it is put in a different file, called specific.c */

/* Texas Instruments edited : Following code copied from specific.c to avoid unnecessary exclusions */
/* FUNCTION: get_num_variables()
 *
 * PARAM1:
 *
 * RETURNS:
 */

int get_num_variables()
{
    int   num = sizeof(variables) / sizeof(struct  variable);

    return num;
}

/* FUNCTION: get_variables_arr()
 *
 * PARAM1: void
 *
 * RETURNS:
 */

/* Borland compiler gives "fixup error" when variables[] is used in snmp.c
 * So, we will use get_variables_arr() to access variables[].
 */

#ifdef __BORLANDC__
struct variable *_loadds get_variables_arr(void)
#else
struct variable   *get_variables_arr(void)
#endif
{
    return   variables;
}

